# Generated by Django 3.1.5 on 2021-02-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
